from __future__ import annotations

import os
from pathlib import Path

import pytest

from anystruct import fe_plate_fields
from anystruct.fe_solver_backend.elements import ShellElement
from anystruct.fe_solver_backend.sesam_fem import (
    SesamFemError,
    import_sesam_fem,
    read_raw_records,
    read_sesam_fem_document,
    write_sesam_fem_document,
)
from anystruct.fe_solver_backend.sesam_fem.sif_importer import read_sesam_sif_stress


REF_CASES = Path(__file__).resolve().parents[1] / "ref_Cases"


def _work_dir() -> Path:
    path = Path(".pytest_tmp_sesam_fem") / str(os.getpid())
    path.mkdir(parents=True, exist_ok=True)
    return path


def _mixed_shell_fem() -> str:
    return "\n".join(
        [
            "IDENT          100               1",
            "DATE          2026              6              23",
            "        Generated by ANYintelligent test",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "TDMATER          1  S355 steel",
            "GELTH           10  2.000000D-02",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GCOORD           3               0               1               0",
            "GCOORD           4               1               1               0",
            "GNODE            1               1               6          123456",
            "GNODE            2               2               6          123456",
            "GNODE            3               3               6          123456",
            "GNODE            4               4               6          123456",
            "GELMNT1        100               0              25               0               1               2               3",
            "GELREF1        100               1              10",
            "GELMNT1        200               0              24               0               1               2               4               3",
            "GELREF1        200               1              10",
            "BNBCD            1               6               1               1               1               0               0               0",
            "FOOBAR          99",
            "IEND",
            "",
        ]
    )


def _transformed_shell_sif() -> str:
    return "\n".join(
        [
            "IDENT          101               1",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "GELTH           10  2.000000D-02",
            "GUNIVEC          5               0               0               1",
            "BNTRCOS          7               1               0               0               0               1               0               0               0               1",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GCOORD           3               1               1               0",
            "GCOORD           4               0               1               0",
            "GELMNT1        100               0              24               0               1               2               3               4",
            "GELREF1        100               1               0               0               0               0               0               0              10               0               0               7",
            "RVSTRESS         1               0             100               0              24               0    1.000000E+08               0               0    1.000000E+08               0",
            "IEND",
            "",
        ]
    )


def _internal_reference_transformed_shell_sif() -> str:
    return "\n".join(
        [
            "IDENT          101               1",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "GELTH           10  2.000000D-02",
            "BNTRCOS          7               1               0               0               0               1               0               0               0               1",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GCOORD           3               1               1               0",
            "GCOORD           4               0               1               0",
            "GELMNT1        200              10              24               0               1               2               3               4",
            "GELREF1         10               1               0               0               0               0               0               0              10               0               0               7",
            "RVSTRESS         1               0              10               0              24               0    1.000000E+08               0               0    1.000000E+08               0",
            "IEND",
            "",
        ]
    )


def _oriented_beam_fem() -> str:
    return "\n".join(
        [
            "IDENT          102               1",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "GBEAMG           1               0    2.000000E-02    1.000000E-06    2.000000E-06    3.000000E-06",
            "GUNIVEC          5               0               0               1",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GELMNT1        300               0              15               0               1               2",
            "GELREF1        300               1               0               0               0               0               0               0               1               0               0               5",
            "IEND",
            "",
        ]
    )


def test_reader_parses_unit_vectors_and_coordinate_transforms() -> None:
    path = _work_dir() / "transformed_shell.SIF"
    path.write_text(_transformed_shell_sif(), encoding="ascii")

    document = read_sesam_fem_document(path)

    assert document.unit_vectors[5].vector == (0.0, 0.0, 1.0)
    assert document.coordinate_transforms[7].matrix == (
        (1.0, 0.0, 0.0),
        (0.0, 1.0, 0.0),
        (0.0, 0.0, 1.0),
    )
    assert document.element_references[100].transform_id == 7


def test_sif_stress_uses_explicit_bntrcos_shell_transform() -> None:
    path = _work_dir() / "transformed_shell.SIF"
    path.write_text(_transformed_shell_sif(), encoding="ascii")

    stress = read_sesam_sif_stress(path).element_stress[100]

    assert stress[0] == pytest.approx(0.0, abs=1.0e-6)
    assert stress[1] == pytest.approx(100.0e6)
    assert stress[3] == pytest.approx(0.0, abs=1.0e-6)


def test_sif_stress_uses_internal_element_reference_for_shell_transform() -> None:
    path = _work_dir() / "internal_ref_transformed_shell.SIF"
    path.write_text(_internal_reference_transformed_shell_sif(), encoding="ascii")

    stress_result = read_sesam_sif_stress(path)
    stress = stress_result.element_stress[200]

    assert stress[0] == pytest.approx(0.0, abs=1.0e-6)
    assert stress[1] == pytest.approx(100.0e6)
    assert stress[3] == pytest.approx(0.0, abs=1.0e-6)


def test_fem_importer_attaches_explicit_shell_transform_metadata() -> None:
    path = _work_dir() / "transformed_shell.SIF"
    path.write_text(_transformed_shell_sif(), encoding="ascii")

    result = import_sesam_fem(path)
    shell = result.model.mesh.elements[100]

    assert getattr(shell, "sesam_transform_ids") == (7,)
    assert getattr(shell, "sesam_local_axes") == {
        "x": (1.0, 0.0, 0.0),
        "y": (0.0, 1.0, 0.0),
        "z": (0.0, 0.0, 1.0),
    }


def test_fem_importer_maps_gunivec_to_beam_orientation() -> None:
    path = _work_dir() / "oriented_beam.FEM"
    path.write_text(_oriented_beam_fem(), encoding="ascii")

    result = import_sesam_fem(path)
    beam = result.model.mesh.elements[300]

    assert getattr(beam, "sesam_transform_ids") == (5,)
    assert beam.cross_section["orientation"] == (0.0, 0.0, 1.0)


def test_read_document_preserves_unknown_and_mixed_shell_topology() -> None:
    path = _work_dir() / "mixed_shells.FEM"
    path.write_text(_mixed_shell_fem(), encoding="ascii")

    document = read_sesam_fem_document(path)

    assert document.record_counts["GELMNT1"] == 2
    assert document.materials[1].elastic_modulus == pytest.approx(210.0e9)
    assert document.nodes[2].coordinates == (1.0, 0.0, 0.0)
    assert document.elements[100].type_code == 25
    assert document.elements[100].node_ids == (1, 2, 3)
    assert document.elements[200].type_code == 24
    assert document.elements[200].node_ids == (1, 2, 4, 3)
    assert document.unknown_records[0].name == "FOOBAR"
    assert any(item.code == "FEM110" for item in document.diagnostics)


def test_import_sesam_fem_builds_native_shell_model() -> None:
    path = _work_dir() / "import_shells.FEM"
    path.write_text(_mixed_shell_fem(), encoding="ascii")

    result = import_sesam_fem(path)

    assert result.model is not None
    assert result.model.mesh.num_nodes == 4
    assert result.model.mesh.num_elements == 2
    assert result.element_count_by_type == {25: 1, 24: 1}
    assert isinstance(result.model.mesh.elements[100], ShellElement)
    assert result.model.mesh.elements[100].thickness == pytest.approx(0.02)
    assert len(result.model.boundary_conditions) == 1


def test_sesam_access_hole_free_edges_split_vertical_plate_fields() -> None:
    nodes = {}
    node_id = 1
    for z_coord in range(5):
        for x_coord in range(5):
            nodes[node_id] = (float(x_coord), 0.0, float(z_coord))
            node_id += 1

    def nid(x_coord: int, z_coord: int) -> int:
        return z_coord * 5 + x_coord + 1

    elements = {}
    element_id = 1
    for z_coord in range(4):
        for x_coord in range(4):
            if 1 <= x_coord <= 2 and 1 <= z_coord <= 2:
                continue
            elements[element_id] = fe_plate_fields.ShellElement(
                element_id,
                (
                    nid(x_coord, z_coord),
                    nid(x_coord + 1, z_coord),
                    nid(x_coord + 1, z_coord + 1),
                    nid(x_coord, z_coord + 1),
                ),
                element_type="S4",
            )
            element_id += 1

    model = fe_plate_fields.FeShellModel(
        nodes=nodes,
        shell_elements=elements,
        elsets={"plate": tuple(elements)},
        shell_sections=(fe_plate_fields.ShellSection("plate", "S355", 0.01),),
        source_path="access_hole.SIF",
    )

    fields = fe_plate_fields.infer_plate_fields(model)

    assert len(fields) > 1
    for field in fields:
        central_band = [
            fe_plate_fields._element_centroid(model, model.shell_elements[element_id])
            for element_id in field.element_ids
            if 1.0 <= fe_plate_fields._element_centroid(model, model.shell_elements[element_id])[0] <= 3.0
        ]
        if not central_band:
            continue
        z_values = [point[2] for point in central_band]
        assert not (min(z_values) < 1.0 and max(z_values) > 3.0)


def test_shell_thickness_for_elements_is_area_weighted() -> None:
    model = fe_plate_fields.FeShellModel(
        nodes={
            1: (0.0, 0.0, 0.0),
            2: (1.0, 0.0, 0.0),
            3: (1.0, 1.0, 0.0),
            4: (0.0, 1.0, 0.0),
            5: (2.0, 0.0, 0.0),
            6: (2.0, 1.0, 0.0),
        },
        shell_elements={
            1: fe_plate_fields.ShellElement(1, (1, 2, 3, 4), element_type="S4"),
            2: fe_plate_fields.ShellElement(2, (2, 5, 6, 3), element_type="S4"),
        },
        elsets={"thin": (1,), "thick": (2,)},
        shell_sections=(
            fe_plate_fields.ShellSection("thin", "S355", 0.01),
            fe_plate_fields.ShellSection("thick", "S355", 0.03),
        ),
    )

    assert fe_plate_fields._shell_section_thickness_for_elements(model, (1, 2)) == pytest.approx(0.02)


def test_dnv_panel_usage_factor_uses_highest_calculated_subcheck() -> None:
    result = {
        "result": {
            "Plate": {"Plate buckling": 0.243},
            "Stiffener": {
                "Overpressure plate side": 0.604,
                "Overpressure stiffener side": 0.601,
                "Resistance between stiffeners": 0.955,
                "Shear capacity": 0.0,
            },
            "Girder": {"Overpressure plate side": 0.0},
            "Local buckling": {"Stiffener": [239.0, 176.0]},
        }
    }

    assert fe_plate_fields._selected_uf_from_buckling_result(result) == pytest.approx(0.955)


def test_writer_roundtrip_and_no_overwrite_guard() -> None:
    work_dir = _work_dir()
    input_path = work_dir / "roundtrip_in.FEM"
    output_path = work_dir / "roundtrip_out.FEM"
    input_path.write_text(_mixed_shell_fem(), encoding="ascii")
    if output_path.exists():
        output_path.unlink()

    document = read_sesam_fem_document(input_path)
    report = write_sesam_fem_document(document, output_path)
    reread = read_sesam_fem_document(output_path)

    assert report.records_written >= len(document.raw_records)
    assert reread.record_counts["IEND"] == 1
    assert reread.elements[200].type_code == 24
    with pytest.raises(SesamFemError) as exc_info:
        write_sesam_fem_document(document, output_path)
    assert exc_info.value.code == "FEM201"


def test_rejects_sin_sif_binary_and_missing_iend() -> None:
    work_dir = _work_dir()
    sin_path = work_dir / "case.SIN"
    sif_path = work_dir / "case.SIF"
    binary_path = work_dir / "binary.FEM"
    missing_iend_path = work_dir / "missing_iend.FEM"
    sin_path.write_text("IDENT          1\nIEND\n", encoding="ascii")
    sif_path.write_text("IDENT          1\nIEND\n", encoding="ascii")
    binary_path.write_bytes(b"\x00\x01\x02not formatted fem")
    missing_iend_path.write_text("IDENT          1\nGNODE           1 0 0 0 0\n", encoding="ascii")

    for path in (sin_path, binary_path):
        with pytest.raises(SesamFemError) as exc_info:
            read_sesam_fem_document(path)
        assert exc_info.value.code == "FEM001"

    with pytest.raises(SesamFemError) as exc_info:
        read_sesam_fem_document(missing_iend_path)
    assert exc_info.value.code == "FEM003"

    document = read_sesam_fem_document(missing_iend_path, strict=False)
    assert any(item.code == "FEM003" for item in document.diagnostics)


def test_element_node_count_mismatch_is_an_error() -> None:
    path = _work_dir() / "bad_element.FEM"
    path.write_text(
        "\n".join(
            [
                "IDENT          1",
                "GNODE          1 0 0 0 0",
                "GNODE          2 0 1 0 0",
                "GELMNT1       10 0 25 0 1 2",
                "IEND",
                "",
            ]
        ),
        encoding="ascii",
    )

    with pytest.raises(SesamFemError) as exc_info:
        read_sesam_fem_document(path)
    assert exc_info.value.code == "FEM104"

    document = read_sesam_fem_document(path, strict=False)
    assert any(item.code == "FEM104" for item in document.diagnostics)


def test_reader_accepts_fixed_width_numeric_fields() -> None:
    path = _work_dir() / "fixed_width.FEM"
    gnode = "GNODE   " + "".join(
        [
            f"{1:16d}",
            f"{0:16d}",
            f"{1.25:16.8E}",
            f"{-2.5:16.8E}",
            f"{0.0:16.8E}",
        ]
    )
    path.write_text("\n".join(["IDENT          1", gnode, "IEND", ""]), encoding="ascii")

    records = read_raw_records(path)
    assert records[1].numeric_fields == pytest.approx((1.0, 0.0, 1.25, -2.5, 0.0))

    document = read_sesam_fem_document(path)
    assert document.nodes[1].coordinates == pytest.approx((1.25, -2.5, 0.0))


def test_reader_classifies_named_hp_bulb_sections_as_l_bulb() -> None:
    path = _work_dir() / "hp_bulb_section.SIF"
    path.write_text(
        "\n".join(
            [
                "IDENT          101               1",
                "TDSECT           4              10  HPbulb160x7x22x6x6",
                "GLSEC           10    1.600000E-01    7.000000E-03    2.900000E-02    1.546379E-02",
                "IEND",
                "",
            ]
        ),
        encoding="ascii",
    )

    document = read_sesam_fem_document(path)

    assert document.sections[10].section_type == "L-bulb"
    assert document.sections[10].web_height == pytest.approx(0.160)


def test_sesam_split_filters_short_intersection_beams_and_keeps_sustained_boundaries() -> None:
    short_flatbar = fe_plate_fields.InferredMember(
        member_id="beam_u_001",
        role="stiffener",
        section_type="FB",
        web_patch_id="beam_1",
        flange_patch_id=None,
        direction=(1.0, 0.0, 0.0),
        station=25.84,
        web_height_m=0.2,
        flange_width_m=0.01,
        run_length_m=0.15,
    )
    sustained_bulb = fe_plate_fields.InferredMember(
        member_id="beam_u_002",
        role="stiffener",
        section_type="L-bulb",
        web_patch_id="beam_2",
        flange_patch_id=None,
        direction=(1.0, 0.0, 0.0),
        station=25.96,
        web_height_m=0.16,
        flange_width_m=0.029,
        run_length_m=9.0,
    )
    boundary = fe_plate_fields.InferredMember(
        member_id="plate_u_001",
        role="plate_boundary",
        section_type="plate",
        web_patch_id="shell_1",
        flange_patch_id=None,
        direction=(1.0, 0.0, 0.0),
        station=25.11,
        web_height_m=0.0,
        flange_width_m=None,
        run_length_m=0.82,
    )

    beams = fe_plate_fields._filter_sesam_sustained_beam_members(
        (short_flatbar, sustained_bulb),
        tolerance=0.04,
        min_required_length=0.60,
    )
    boundaries = fe_plate_fields._filter_sesam_sustained_boundary_members(
        (boundary,),
        tolerance=0.04,
        min_required_length=0.60,
    )

    assert [member.section_type for member in beams] == ["L-bulb"]
    assert boundaries == [boundary]


@pytest.mark.skipif(not REF_CASES.exists(), reason="SESAM reference cases are not available")
def test_q8_sif_cylinder_panel_uses_real_ring_frame_and_membrane_stresses() -> None:
    session = fe_plate_fields.create_fea_buckling_session(
        REF_CASES / "allQuad2ndorder_pressure_force_gravity_girder_stiffners.SIF",
        geometry_type="cylinder",
        run_buckling=True,
    )

    assert len(session.model.shell_elements) == 640
    assert len(session.geometry.skin_element_ids) == 640
    assert len(session.panels) == 16

    panel = session.panel("cyl_field_009")
    ring_frame = panel.anystructure_input["ring_frame"]
    assert ring_frame["web_height_mm"] == pytest.approx(400.0, rel=1.0e-6)
    assert ring_frame["flange_width_mm"] == pytest.approx(100.0, rel=1.0e-6)
    assert ring_frame["source_member_id"] != "beam_ring_001"
    assert panel.usage_factor is not None
    assert panel.stress is not None
    assert panel.stress.sample_count == 40
    assert panel.stress.axial_stress_mpa == pytest.approx(-1.125, abs=1.0e-3)
    assert panel.stress.hoop_stress_mpa == pytest.approx(-6.102, abs=1.0e-3)
    assert panel.stress.torsional_shear_mpa == pytest.approx(1.939, abs=1.0e-3)


@pytest.mark.skipif(not REF_CASES.exists(), reason="SESAM reference cases are not available")
def test_highload_sif_cylinder_maps_sesam_sigyy_to_axial_stress() -> None:
    session = fe_plate_fields.create_fea_buckling_session(
        REF_CASES / "allQuadLinear_pressure_force_gravity_girder_stiffners_HighLoad.SIF",
        geometry_type="cylinder",
        run_buckling=False,
    )

    assert len(session.model.shell_elements) == 640
    assert len(session.geometry.skin_element_ids) == 640
    assert len(session.panels) == 16

    panel = session.panel("cyl_field_002")
    assert panel.stress is not None
    assert panel.stress.sample_count == 40
    assert panel.stress.axial_stress_mpa == pytest.approx(-248.0, abs=0.1)
    assert panel.stress.hoop_stress_mpa == pytest.approx(-26.66, abs=0.1)
    assert panel.stress.torsional_shear_mpa == pytest.approx(39.12, abs=0.1)

    axial_max = max(abs(panel.stress.axial_stress_mpa) for panel in session.panels)
    hoop_max = max(abs(panel.stress.hoop_stress_mpa) for panel in session.panels)
    shear_max = max(abs(panel.stress.torsional_shear_mpa) for panel in session.panels)
    assert axial_max > 5.0 * hoop_max
    assert shear_max == pytest.approx(96.8, abs=0.5)


@pytest.mark.skipif(not REF_CASES.exists(), reason="SESAM reference cases are not available")
@pytest.mark.parametrize(
    ("filename", "shell_count"),
    [
        ("allTriLinear_pressure_force_gravity_girder_stiffners.SIF", 1412),
        ("allTri2ndorder_pressure_force_gravity_girder_stiffners.SIF", 1412),
        ("mixed2ndOrder_pressure_force_gravity_girder_stiffner.SIF", 630),
    ],
)
def test_sif_cylinder_import_keeps_tri_mixed_skin_and_populated_panels(
    filename: str,
    shell_count: int,
) -> None:
    session = fe_plate_fields.create_fea_buckling_session(
        REF_CASES / filename,
        geometry_type="cylinder",
        run_buckling=False,
    )

    assert len(session.model.shell_elements) == shell_count
    assert len(session.geometry.skin_element_ids) == shell_count
    assert len(session.panels) == 16
    assert all(field.element_ids for field in session.fields)
    assert all(panel.stress is not None and panel.stress.sample_count > 0 for panel in session.panels)
