from __future__ import annotations

import os
from pathlib import Path

import pytest

from anystruct.fe_solver_backend.elements import ShellElement
from anystruct.fe_solver_backend.sesam_fem import (
    SesamFemError,
    import_sesam_fem,
    read_raw_records,
    read_sesam_fem_document,
    write_sesam_fem_document,
)


def _work_dir() -> Path:
    path = Path(".pytest_tmp_sesam_fem") / str(os.getpid())
    path.mkdir(parents=True, exist_ok=True)
    return path


def _mixed_shell_fem() -> str:
    return "\n".join(
        [
            "IDENT          100               1",
            "DATE          2026              6              23",
            "        Generated by ANYintelligent test",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "TDMATER          1  S355 steel",
            "GELTH           10  2.000000D-02",
            "GCOORD           0",
            "GNODE            1               0               0               0               0",
            "GNODE            2               0               1               0               0",
            "GNODE            3               0               0               1               0",
            "GNODE            4               0               1               1               0",
            "GELMNT1        100               0              25               0               1               2               3",
            "GELREF1        100               1              10",
            "GELMNT1        200               0              24               0               1               2               4               3",
            "GELREF1        200               1              10",
            "BNBCD            1               1               1               1               0               0               0",
            "FOOBAR          99",
            "IEND",
            "",
        ]
    )


def test_read_document_preserves_unknown_and_mixed_shell_topology() -> None:
    path = _work_dir() / "mixed_shells.FEM"
    path.write_text(_mixed_shell_fem(), encoding="ascii")

    document = read_sesam_fem_document(path)

    assert document.record_counts["GELMNT1"] == 2
    assert document.materials[1].elastic_modulus == pytest.approx(210.0e9)
    assert document.nodes[2].coordinates == (1.0, 0.0, 0.0)
    assert document.elements[100].type_code == 25
    assert document.elements[100].node_ids == (1, 2, 3)
    assert document.elements[200].type_code == 24
    assert document.elements[200].node_ids == (1, 2, 4, 3)
    assert document.unknown_records[0].name == "FOOBAR"
    assert any(item.code == "FEM110" for item in document.diagnostics)


def test_import_sesam_fem_builds_native_shell_model() -> None:
    path = _work_dir() / "import_shells.FEM"
    path.write_text(_mixed_shell_fem(), encoding="ascii")

    result = import_sesam_fem(path)

    assert result.model is not None
    assert result.model.mesh.num_nodes == 4
    assert result.model.mesh.num_elements == 2
    assert result.element_count_by_type == {25: 1, 24: 1}
    assert isinstance(result.model.mesh.elements[100], ShellElement)
    assert result.model.mesh.elements[100].thickness == pytest.approx(0.02)
    assert len(result.model.boundary_conditions) == 1


def test_writer_roundtrip_and_no_overwrite_guard() -> None:
    work_dir = _work_dir()
    input_path = work_dir / "roundtrip_in.FEM"
    output_path = work_dir / "roundtrip_out.FEM"
    input_path.write_text(_mixed_shell_fem(), encoding="ascii")
    if output_path.exists():
        output_path.unlink()

    document = read_sesam_fem_document(input_path)
    report = write_sesam_fem_document(document, output_path)
    reread = read_sesam_fem_document(output_path)

    assert report.records_written >= len(document.raw_records)
    assert reread.record_counts["IEND"] == 1
    assert reread.elements[200].type_code == 24
    with pytest.raises(SesamFemError) as exc_info:
        write_sesam_fem_document(document, output_path)
    assert exc_info.value.code == "FEM201"


def test_rejects_sin_sif_binary_and_missing_iend() -> None:
    work_dir = _work_dir()
    sin_path = work_dir / "case.SIN"
    sif_path = work_dir / "case.SIF"
    binary_path = work_dir / "binary.FEM"
    missing_iend_path = work_dir / "missing_iend.FEM"
    sin_path.write_text("IDENT          1\nIEND\n", encoding="ascii")
    sif_path.write_text("IDENT          1\nIEND\n", encoding="ascii")
    binary_path.write_bytes(b"\x00\x01\x02not formatted fem")
    missing_iend_path.write_text("IDENT          1\nGNODE           1 0 0 0 0\n", encoding="ascii")

    for path in (sin_path, sif_path, binary_path):
        with pytest.raises(SesamFemError) as exc_info:
            read_sesam_fem_document(path)
        assert exc_info.value.code == "FEM001"

    with pytest.raises(SesamFemError) as exc_info:
        read_sesam_fem_document(missing_iend_path)
    assert exc_info.value.code == "FEM003"

    document = read_sesam_fem_document(missing_iend_path, strict=False)
    assert any(item.code == "FEM003" for item in document.diagnostics)


def test_element_node_count_mismatch_is_an_error() -> None:
    path = _work_dir() / "bad_element.FEM"
    path.write_text(
        "\n".join(
            [
                "IDENT          1",
                "GNODE          1 0 0 0 0",
                "GNODE          2 0 1 0 0",
                "GELMNT1       10 0 25 0 1 2",
                "IEND",
                "",
            ]
        ),
        encoding="ascii",
    )

    with pytest.raises(SesamFemError) as exc_info:
        read_sesam_fem_document(path)
    assert exc_info.value.code == "FEM104"

    document = read_sesam_fem_document(path, strict=False)
    assert any(item.code == "FEM104" for item in document.diagnostics)


def test_reader_accepts_fixed_width_numeric_fields() -> None:
    path = _work_dir() / "fixed_width.FEM"
    gnode = "GNODE   " + "".join(
        [
            f"{1:16d}",
            f"{0:16d}",
            f"{1.25:16.8E}",
            f"{-2.5:16.8E}",
            f"{0.0:16.8E}",
        ]
    )
    path.write_text("\n".join(["IDENT          1", gnode, "IEND", ""]), encoding="ascii")

    records = read_raw_records(path)
    assert records[1].numeric_fields == pytest.approx((1.0, 0.0, 1.25, -2.5, 0.0))

    document = read_sesam_fem_document(path)
    assert document.nodes[1].coordinates == pytest.approx((1.25, -2.5, 0.0))
